[project]
name = "ugaritic-nb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
"text-fabric[all]",
"plotly",
"pandas",
"jupyter"
]
